export { default as ArrowRightLinearGradientIcon } from "./arrowRightLinearGradient";
export { default as ArrowUpRightIcon } from "./arrowUpRight";
export { default as CheckerIcon } from "./checker";
export { default as DataLockIcon } from "./dataLock";
export { default as DataScientistIcon } from "./dataScientist";
export { default as DiscordIcon } from "./discord";
export { default as FraudDetectionIcon } from "./fraudDetection";
export { default as TelegramIcon } from "./telegram";
export { default as XIcon } from "./x";
